////////////////////////////////////////
//File generated by SpyDrNet
//Netlist: netlist
////////////////////////////////////////
(* STRUCTURAL_NETLIST = "yes" *)
module widget
(
    A,
    O
);
input A;
output O;
wire cable;
wire cable2;
AND2 and2
(
    .O(cable [0] )
);
endmodule
module AND2
(
    A,
    O
);
input A;
output O;
endmodule
