////////////////////////////////////////
//File generated by SpyDrNet
//Netlist: netlist
////////////////////////////////////////
(* STRUCTURAL_NETLIST = "yes" *)
module widget
(
    port_a,
    port_o
);
input port_a;
input port_o;
endmodule
